version: '2.1'

services:
  cropper:
    build: 
      context: ./cropper
      dockerfile: Dockerfile
    privileged: true
    restart: always
    ports:
      - "5000:5000"

  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - cropper
    ports:
      - "80:80"
    restart: always
