upload_max_filesize = 100M
post_max_size = 120M
memory_limit = 512M
max_execution_time = 300
max_input_time = 300

file_uploads = On
upload_tmp_dir = /tmp

; Good for large PDFs/TIFFs
enable_post_data_reading = On
