name: Docker Build Multi-Platform

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner to use'
        required: false
        default: 'self-hosted'
        type: choice
        options:
          - 'self-hosted'
          - 'ubuntu-latest'

env:
  REGISTRY: docker.io
  REGISTRY_IMAGE: bprtkop
  GIT_SHA: ${{ github.sha }}
  TAG: ${{ github.ref_name }}
  DEFAULT_RUNNER: 'ubuntu-latest'
  MATRIX_RUNNER: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.runner || vars.DEFAULT_RUNNER }}

jobs:
  determine-runner:
    runs-on: ${{ vars.DEFAULT_RUNNER }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix={\"runner\":[\"${{ env.MATRIX_RUNNER }}\"]}" >> $GITHUB_OUTPUT
